[default]
elasticsearch=${ARKIME_ELASTICSEARCH}

# де arkime шукає/зберігає pcap
pcapDir=/opt/arkime/raw

# зручно фіксувати тут ім'я ноди, щоб viewer/capture збігались
nodeName=ctfkit

# viewer
viewHost=0.0.0.0
viewPort=8005

# корисно: щоб не впиратись у права, відразу можна ось тут
dropUser=nobody
dropGroup=daemon
